name: Approve

on:
    pull_request:
        types:
            - labeled

jobs:
    approve:
        if: contains(github.event.pull_request.labels.*.name, 'approved')
        runs-on: ubuntu-slim
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v5
            - name: Approve
              run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
