name: Approve

on:
    pull_request:
        types:
            - labeled

jobs:
    approve:
        if: contains(github.event.pull_request.labels.*.name, 'approved')
        runs-on: ubuntu-slim
        permissions:
            contents: write
            pull-requests: write
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v6

            - name: Approve
              run: gh pr review --approve "${{ github.event.pull_request.html_url }}"

            - name: Unlabel
              run: gh pr edit "${{ github.event.pull_request.html_url }}" --remove-label "approved"
